Add StealthEX to the exchanges list
bchinfo/bch.info pull request #164
Opened 2022-08-31 11:57 UTC by Vtasz

2022-08-31 22:24 UTC, merc1er requested changes
Invalid JSON. Did you try to build the site? CD failed.

2022-09-01 11:03 UTC, Vtasz commented
> Invalid JSON. Did you try to build the site? CD failed.

Yeah, wanted to create a pull request to add our service on the website. Did it similarly to Simpleswap, or so I thought. Unfortunatelt my github knowledge is rather shallow. I've asked our devs to assist and they should be able to do it properly

2022-10-27 19:19 UTC, danger89 requested changes

2022-10-27 19:19 UTC, danger89 commented on app/data/exchanges.json
> +      "link": "https://stealthex.io/"
Missing `}` after line 109.

2022-10-31 11:13 UTC, closed without merging

2022-10-31 11:13 UTC, Vtasz commented
Had one of our devs, has opened a proper pull request! 
Thank you!